<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>css</string>
		<string>css.erb</string>
		<string>less</string>
		<string>scss</string>
		<string>sass</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*(?!\*)|\{\s*($|/\*(?!.*?\*/.*\S))</string>
	<key>foldingStopMarker</key>
	<string>(?&lt;!\*)\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>mCSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(?=\s*[:.*#a-zA-Z])</string>
			<key>end</key>
			<string>(?=\{)</string>
			<key>name</key>
			<string>meta.selector.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-block</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(a|abbr|acronym|address|area|b|base|big|blockquote|body|br|button|caption|cite|code|col|colgroup|dd|del|dfn|div|dl|dt|em|fieldset|form|frame|frameset|(h[1-6])|head|hr|html|i|iframe|img|input|ins|kbd|label|legend|li|link|map|meta|noframes|noscript|object|ol|optgroup|option|p|param|pre|q|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|ul|var|article|aside|audio|canvas|command|datalist|details|embed|figcaption|figure|footer|header|hgroup|keygen |mark|menu|meter|nav|output|progress|rp|rt|ruby|section|summary|time|video|wbr)\b</string>
					<key>name</key>
					<string>entity.name.tag.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.)[a-zA-Z0-9_-]+</string>
					<key>name</key>
					<string>entity.other.attribute-name.class.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#)[a-zA-Z][a-zA-Z0-9_-]*</string>
					<key>name</key>
					<string>entity.other.attribute-name.id.css</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>entity.name.tag.wildcard.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:+)\b(after|before|first-child|first-letter|first-line|selection)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-element.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:)\b(active|hover|link|visited|focus)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-class.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.attribute.css</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.operator.css</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.attribute-value.css</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.attribute-value.css</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.css</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(\[)\s*(-?[_a-z\\[[:^ascii:]]][_a-z0-9\-\\[[:^ascii:]]]*)(?:\s*([~|^$*]?=)\s*(?:(-?[_a-z\\[[:^ascii:]]][_a-z0-9\-\\[[:^ascii:]]]*)|((?&gt;(['"])(?:[^\\]|\\.)*?(\6)))))?\s*(\])</string>
					<key>name</key>
					<string>meta.attribute-selector.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.css.mcss</string>
	<key>uuid</key>
	<string>1A35587E-3FBD-468A-9D64-97E34AC1734C</string>
</dict>
</plist>
